### PR TITLE
Adding turbolinks:load to document.on('ready')

### PR DESCRIPTION
**Pull request by abreckner**
Hello, 
I forked your excellent project to get it working with turbolinks and I thought I would create a pull request in case you wanted to merge it in. 

I did try using the jquery.turbolinks gem, but I believe it had some problems with the module pattern used to instantiate the forms (in forms.js). Specifically https://github.com/kossnocorp/jquery.turbolinks#events-firing-twice-or-more

In any case, I will be using my fork for now. Please let me know if you do merge it in as I would much prefer to be using the source.

Thanks very much

Tony Breckner

### CODE REVIEW

**Comment by jameswilliamiii** [comment]
Thanks for taking the time to make these changes. Hopefully these gets merged in soon.

**Comment by rubendinho** [comment]
Is this for Turbolinks 5?

**Comment by abreckner** [comment]
Hi, 
Sorry, I only just saw these comments. Yes, this is for Turbolinks 5

**Comment by rubendinho** [comment]
It looks like similar changes got added and then removed in a following commit.  Not sure why though.

**Pull request closed without merging**
