### PR TITLE
Added a turbo links event handler for when the page changes

### PR DESCRIPTION
**Pull request by mtuck063**

### CODE REVIEW

**Comment by xamenrax** [comment]
Isn't it better to send this pull-request to materialize original repo first?

**Comment by mtuck063** [comment]
No it is not, because 'page:change' is a turbolinks event handler that comes with rails.

**Comment by xamenrax** [comment]
@mtuck063  Don't we need to update all (almost) event handlers to make it fit with turbolinks so?

**Comment by mtuck063** [comment]
True say.

**Pull request closed without merging**
