### PR TITLE
fix error on file input when change is triggered and file input is empty

### PR DESCRIPTION
**Pull request by Migoo**
Hi,

We got an error when we repaint in React the file field input. It trigger a change event, but the input is empty, so it trigger an undefined error on files[0]

Thanks for watching :)

Best regards

### CODE REVIEW

**Comment by xamenrax** [comment]
I think it's better to request this pull in original MaterializeCSS framework's repo, isn't it?

**Comment by Migoo** [comment]
Hello,

yes great idea, I have already made it: https://github.com/mkhairi/materialize-sass/pull/40#issuecomment-111074567.

But in the meanwhile, can you merge it ?

Cheers

**Comment by xamenrax** [comment]
@Migoo , sure, thanks for participating!

**Comment by Migoo** [comment]
Thanks :+1:

**Pull request merged**
